<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:0 auto;padding:20px">
<h2 style="color:#2563eb">Monthly P&L Report — {{ $month }}</h2>
<p>Dear {{ $owner->name }},</p>
<p>Please find attached the Profit & Loss report for <strong>{{ $month }}</strong> for <strong>{{ $tenant->name }}</strong>.</p>

<table style="width:100%;border-collapse:collapse;margin:20px 0">
    <tr style="background:#f3f4f6">
        <th style="text-align:left;padding:10px;border:1px solid #e5e7eb">Metric</th>
        <th style="text-align:right;padding:10px;border:1px solid #e5e7eb">Amount (TZS)</th>
    </tr>
    <tr>
        <td style="padding:10px;border:1px solid #e5e7eb">Revenue</td>
        <td style="padding:10px;border:1px solid #e5e7eb;text-align:right">{{ number_format($data['revenue'], 2) }}</td>
    </tr>
    <tr style="background:#f9fafb">
        <td style="padding:10px;border:1px solid #e5e7eb">Cost of Goods Sold</td>
        <td style="padding:10px;border:1px solid #e5e7eb;text-align:right">{{ number_format($data['cogs'], 2) }}</td>
    </tr>
    <tr>
        <td style="padding:10px;border:1px solid #e5e7eb;font-weight:bold">Gross Profit</td>
        <td style="padding:10px;border:1px solid #e5e7eb;text-align:right;font-weight:bold;color:{{ $data['grossProfit'] >= 0 ? '#16a34a' : '#dc2626' }}">
            {{ number_format($data['grossProfit'], 2) }}
        </td>
    </tr>
    <tr style="background:#f9fafb">
        <td style="padding:10px;border:1px solid #e5e7eb">Operating Expenses</td>
        <td style="padding:10px;border:1px solid #e5e7eb;text-align:right;color:#dc2626">{{ number_format($data['expenses'], 2) }}</td>
    </tr>
    <tr>
        <td style="padding:10px;border:1px solid #e5e7eb;font-weight:bold">Net Profit</td>
        <td style="padding:10px;border:1px solid #e5e7eb;text-align:right;font-weight:bold;font-size:1.1em;color:{{ $data['netProfit'] >= 0 ? '#16a34a' : '#dc2626' }}">
            {{ number_format($data['netProfit'], 2) }}
        </td>
    </tr>
</table>

<p style="color:#6b7280;font-size:.9em">Top expense category: <strong>{{ $data['topExpenseCategory'] }}</strong></p>
<p>The full PDF report is attached to this email.</p>
<p style="color:#6b7280;font-size:.85em">Generated by SmartStock ERP</p>
</body>
</html>
