<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; margin: 20mm; color: #333; }
  h1 { font-size: 18px; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td { padding: 7px 10px; border: 1px solid #ddd; }
  th { background: #f5f5f5; font-weight: bold; text-align: left; }
  .label { width: 35%; background: #fafafa; font-weight: 600; }
  .value { width: 65%; }
  .status-approved { color: #16a34a; font-weight: bold; }
  .status-rejected { color: #dc2626; font-weight: bold; }
  .status-pending  { color: #d97706; font-weight: bold; }
  .audit-section { margin-top: 20px; }
  .audit-section h2 { font-size: 13px; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-bottom: 8px; }
  .footer { margin-top: 30px; font-size: 9px; color: #999; border-top: 1px solid #eee; padding-top: 8px; }
</style>
</head>
<body>

<h1>Expense Record</h1>
<p class="subtitle">SmartStock ERP &mdash; Expense #{{ $expense->id }}</p>

<table>
    <tr><td class="label">Expense ID</td><td class="value">#{{ $expense->id }}</td></tr>
    <tr><td class="label">Category</td><td class="value">{{ $expense->category }}</td></tr>
    <tr><td class="label">Description</td><td class="value">{{ $expense->description }}</td></tr>
    <tr><td class="label">Amount (TZS)</td><td class="value" style="font-weight:bold;font-size:14px;">{{ number_format($expense->amount, 2) }}</td></tr>
    <tr><td class="label">Expense Date</td><td class="value">{{ \Carbon\Carbon::parse($expense->expense_date)->format('d F Y') }}</td></tr>
    <tr>
        <td class="label">Status</td>
        <td class="value">
            <span class="status-{{ $expense->status === 'approved' ? 'approved' : ($expense->status === 'rejected' ? 'rejected' : 'pending') }}">
                {{ strtoupper(str_replace('_', ' ', $expense->status)) }}
            </span>
        </td>
    </tr>
    @if($expense->branch)
    <tr><td class="label">Branch</td><td class="value">{{ $expense->branch->name }}</td></tr>
    @endif
    @if($expense->notes)
    <tr>
        <td class="label">{{ $expense->status === 'rejected' ? 'Rejection Reason' : 'Notes' }}</td>
        <td class="value">{{ $expense->notes }}</td>
    </tr>
    @endif
    <tr>
        <td class="label">Receipt Attached</td>
        <td class="value">{{ $expense->receipt_path ? 'Yes' : 'No' }}</td>
    </tr>
</table>

<div class="audit-section">
    <h2>Audit Trail</h2>
    <table>
        <thead>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="label">Created By</td>
                <td>{{ $expense->createdBy?->name ?? '—' }}</td>
            </tr>
            <tr>
                <td class="label">Created At</td>
                <td>{{ $expense->created_at->format('d M Y, H:i') }}</td>
            </tr>
            @if($expense->approved_at || $expense->approvedBy)
            <tr>
                <td class="label">{{ $expense->status === 'rejected' ? 'Acted On By' : 'Approved By' }}</td>
                <td>{{ $expense->approvedBy?->name ?? '—' }}</td>
            </tr>
            <tr>
                <td class="label">{{ $expense->status === 'rejected' ? 'Rejected At' : 'Approved At' }}</td>
                <td>{{ $expense->approved_at?->format('d M Y, H:i') ?? '—' }}</td>
            </tr>
            @endif
            <tr>
                <td class="label">Last Updated</td>
                <td>{{ $expense->updated_at->format('d M Y, H:i') }}</td>
            </tr>
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by SmartStock ERP on {{ now()->format('d M Y H:i') }} &mdash; This document is for internal accounting purposes only.
</div>

</body>
</html>
